---
title: "vicsek simulation report"
author: "Pei Tan"
# date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output: rmdformats::robobook
editor_options: 
chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(ggplot2)
library(viridis)

```



The simulation pipline is constructed on python, plot by R.


# vicsek simulation -- density



```{r density}


accu_df <- read.csv("num_accu_mat.csv")[,-1]

repeat_time = 10

accu_df <- accu_df[accu_df$time < 3000, ]

accu_df$perc5 <- apply(accu_df[, 1:repeat_time], 1, function(x) quantile(x, probs = c(0.05)))
accu_df$perc95 <- apply(accu_df[, 1:repeat_time], 1, function(x) quantile(x, probs = c(0.95)))
accu_df$middle <- apply(accu_df[, 1:repeat_time], 1, function(x) quantile(x, probs = c(0.5)))
accu_df$mean <- apply(accu_df[, 1:repeat_time], 1, function(x) mean(x))

ggplot(accu_df, aes(x=time, y=middle, group=num, color=num)) +
  geom_point()+geom_line()+
  scale_color_viridis(option = "D") +
  labs(x = "simulation time", 
       y = "kmeans-cluster accuracy", 
       title = "Different density scale") +
  theme_minimal()

```


```{r num require time}


accu_df <- read.csv("num_reach_time.csv")[,-1]

accu_df <- accu_df[accu_df$time >= 50, ]

accu_df$perc5 <- apply(accu_df[, 1:100], 1, function(x) quantile(x, probs = c(0.05)))
accu_df$perc95 <- apply(accu_df[, 1:100], 1, function(x) quantile(x, probs = c(0.95)))
accu_df$middle <- apply(accu_df[, 1:100], 1, function(x) quantile(x, probs = c(0.5)))
accu_df$mean <- apply(accu_df[, 1:100], 1, function(x) mean(x))


ggplot(accu_df, aes(x=time, y=middle)) +
  geom_point(color="#f37735", size=4) +
  geom_ribbon(aes(ymin = perc5, ymax = perc95), fill="#f37735", alpha = 0.2) +
  labs(x = "density (density = total ptcl amount / area)", 
       y = "Required time", 
       title = "") +
  theme_bw()


```

# vicsek simulation -- noise



```{r noise}


accu_df <- read.csv("noise_accu_mat.csv")[,-1]

repeat_time = 10

accu_df$perc5 <- apply(accu_df[, 1:repeat_time], 1, function(x) quantile(x, probs = c(0.05)))
accu_df$perc95 <- apply(accu_df[, 1:repeat_time], 1, function(x) quantile(x, probs = c(0.95)))
accu_df$middle <- apply(accu_df[, 1:repeat_time], 1, function(x) quantile(x, probs = c(0.5)))
accu_df$mean <- apply(accu_df[, 1:repeat_time], 1, function(x) mean(x))

ggplot(accu_df, aes(x=time, y=middle, group=noise, color=noise)) +
  geom_point()+geom_line()+
  scale_color_viridis(option = "D") +
  labs(x = "simulation time", 
       y = "kmeans-cluster accuracy", 
       title = "Different noise scale") +
  theme_minimal()

```


# vicsek simulation -- radius


```{r radius}


accu_df <- read.csv("radius2_accu_mat.csv")[,-1]

repeat_time = 10


accu_df$perc5 <- apply(accu_df[, 1:repeat_time], 1, function(x) quantile(x, probs = c(0.05)))
accu_df$perc95 <- apply(accu_df[, 1:repeat_time], 1, function(x) quantile(x, probs = c(0.95)))
accu_df$middle <- apply(accu_df[, 1:repeat_time], 1, function(x) quantile(x, probs = c(0.5)))
accu_df$mean <- apply(accu_df[, 1:repeat_time], 1, function(x) mean(x))

ggplot(accu_df, aes(x=time, y=middle, group=radius, color=radius)) +
  geom_point()+geom_line()+
  scale_color_viridis(option = "D") +
  labs(x = "simulation time", 
       y = "kmeans-cluster accuracy", 
       title = "Different radius scale") +
  theme_minimal()
```



```{r radius_eta}

#### radius when eta = [0.1, 0.5]
accu_df <- read.csv("radius_accu_mat.csv")[,-1]

repeat_time = 10

accu_df <- accu_df[accu_df$time < 4000, ]

accu_df$perc5 <- apply(accu_df[, 1:repeat_time], 1, function(x) quantile(x, probs = c(0.05)))
accu_df$perc95 <- apply(accu_df[, 1:repeat_time], 1, function(x) quantile(x, probs = c(0.95)))
accu_df$middle <- apply(accu_df[, 1:repeat_time], 1, function(x) quantile(x, probs = c(0.5)))
accu_df$mean <- apply(accu_df[, 1:repeat_time], 1, function(x) mean(x))

ggplot(accu_df, aes(x=time, y=middle, group=radius, color=radius)) +
  geom_point()+geom_line()+
  scale_color_viridis(option = "D") +
  labs(x = "simulation time", 
       y = "kmeans-cluster accuracy", 
       title = "Different radius scale with noise difference") +
  theme_minimal()

select_df <- accu_df[accu_df$middle >= 1, ]
table(factor(select_df$radius))

```








